import 'package:flutter/material.dart';

/// Central localization manager for the Smart Bee application.
class Lang {
  static String t(BuildContext context, String key) {
    final locale = Localizations.localeOf(context);
    return _values[locale.languageCode]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'welcome': 'Welcome to,',
      'total': 'Total',
      'region': 'Region',
      'algeria': 'Algeria',
      'faq': 'Beekeeping FAQ',
      'faq_guide_title': 'Beekeeping Guide',
      'admin_panel': 'Admin Panel',
      'logout_admin': 'Logout Admin',
      'switch_light': 'Switch to Light',
      'switch_dark': 'Switch to Dark',
      'updated': 'Updated:',
      'offline': 'OFFLINE',
      'admin_settings': 'ADMIN SETTINGS',
      'push_alerts': 'Push Alerts (ESP32)',
      'management': 'MANAGEMENT',
      'change_lang': 'Change Language',
      'analysis': 'Analysis',
      'temp_label': 'Temperature',
      'hum_label': 'Humidity',
      'min': 'MIN',
      'avg': 'AVG',
      'max': 'MAX',
      'offline_mode': 'You are offline. Showing cached data.',
      'online_mode': 'Connected! Data is now live.',
      'admin_code_hint': 'Admin Access Code',
      'cancel': 'Cancel',
      'access': 'Access',
      'admin_settings_title': 'Threshold Settings',
      'temp_limits': 'Temperature Limits (°C)',
      'hum_limits': 'Humidity Limits (%)',
      'min_val': 'Min Value',
      'max_val': 'Max Value',
      'save_btn': 'SAVE TO FIREBASE',
      'save_success': '✅ Settings Updated Successfully',
      'save_error': '❌ Error saving settings',
      'load_error': 'Error loading settings',
      'invalid_input': '⚠️ Please enter valid numbers',
      'no_records': 'No records found for this day.',
      'connection_error': 'Connection error or invalid data.',
      'trends_label': 'Temperature & Humidity Trends',
      'setup_title': 'Initial Setup',
      'setup_desc': 'To ensure you receive critical alerts, please enable notifications and allow background activity.',
      'enable_notif': 'Enable Notifications',
      'allow_background': 'Allow Background Activity',
      'done_btn': 'Done',
    },
    'ar': {
      'welcome': 'مرحباً بك في،',
      'total': 'الإجمالي',
      'region': 'المنطقة',
      'algeria': 'الجزائر',
      'faq': 'الأسئلة الشائعة حول النحل',
      'faq_guide_title': 'دليل تربية النحل',
      'admin_panel': 'لوحة المسؤول',
      'logout_admin': 'تسجيل خروج المسؤول',
      'switch_light': 'الوضع الفاتح',
      'switch_dark': 'الوضع الليلي',
      'updated': 'تحديث:',
      'offline': 'غير متصل',
      'admin_settings': 'إعدادات المسؤول',
      'push_alerts': 'تنبيهات (ESP32)',
      'management': 'الإدارة',
      'change_lang': 'تغيير اللغة',
      'analysis': 'تحليل البيانات',
      'temp_label': 'درجة الحرارة',
      'hum_label': 'الرطوبة',
      'min': 'الأدنى',
      'avg': 'المتوسط',
      'max': 'الأقصى',
      'offline_mode': 'أنت غير متصل. يتم عرض البيانات المخزنة.',
      'online_mode': 'تم الاتصال! البيانات الآن محدثة.',
      'admin_code_hint': 'رمز دخول المسؤول',
      'cancel': 'إلغاء',
      'access': 'دخول',
      'admin_settings_title': 'إعدادات حدود التنبيه',
      'temp_limits': 'حدود درجة الحرارة (م°)',
      'hum_limits': 'حدود الرطوبة (%)',
      'min_val': 'الحد الأدنى',
      'max_val': 'الحد الأقصى',
      'save_btn': 'حفظ الإعدادات في Firebase',
      'save_success': '✅ تم تحديث الإعدادات بنجاح',
      'save_error': '❌ خطأ في حفظ الإعدادات',
      'load_error': 'خطأ في تحميل الإعدادات',
      'invalid_input': '⚠️ يرجى إدخال أرقام صحيحة',
      'no_records': 'لا توجد سجلات لهذا اليوم.',
      'connection_error': 'خطأ في الاتصال أو البيانات غير صالحة.',
      'trends_label': 'مخطط تغير الحرارة والرطوبة',
      'setup_title': 'إعدادات التشغيل',
      'setup_desc': 'لضمان وصول التنبيهات الضرورية، يرجى تفعيل الإشعارات والسماح للتطبيق بالعمل في الخلفية.',
      'enable_notif': 'تفعيل الإشعارات',
      'allow_background': 'السماح بالعمل في الخلفية',
      'done_btn': 'تم',
    }
  };
}
